name: UniverseMG
version: 1.2
authors: [SorryIm2Fresh, Mafrans, EthanYT]
main: com.Shadersoft.UniverseMG.UniverseMG
softdepend: [Aero]

commands:
    universemg:
        description: Shows information about the plugin.
        usage: /<command>
        aliases: umg
    addadmin:
        description: Adds an admin.
        usage: /<command> <player> <rank>
    removeadmin:
        description: Removes an admin.
        usage: /<command> <player>
    ban:
        description: Bans a player.
        usage: /<command> <player> <reason>
        aliases: gtfo
    unban:
        description: Unbans a banned player.
        usage: /<command> <player>
    banhistory:
        description: Checks the ban history of a player.
        usage: /<command> <player>
    adminlist:
        description: Gets the admin list.
        usage: /<command> <list>
    sban:
        description: Ban a player without the broadcast.
        usage: /<command> <player> <reason>
        aliases: silentban
    kick:
        description: Kick a player.
        usage: /<command> <player> <reason>
    mute:
        description: Mute a player.
        usage: /<command> <player>|list|off|purge [player]
        aliases: stfu
    maintenance:
        description: Turn maintenance on/off.
        usage: /<command> <on|off>
        aliases: [closeserver,adminmode]
    tag:
        description: Set your tag.
        usage: /<command> <tag>|clean|clear>
    broadcast:
        description: Broadcast a message to the server
        usage: /<command> <message>
        aliases: bc, announce, an
    filter:
        description: Filter away some things.
        usage: /<command> <swear>
    playerlist:
        description: List all players
        usage: /<command>
    overlord:
        usage: /<command> <do|console|addme|removeme>
    flip:
        description: Flip a lever.
        usage: /<command> [x] [y] [z]
    forums:
        description: Get the forum link.
        usage: /<command>
        aliases: forum
    twitter:
        description: Get the server twitter.
        usage: /<command>
        aliases: twitterhandle
    points:
        description: Give a player points.
        usage: /<command> <type> <player> <amount>
    vanish:
        description: Hides the player.
        usage: /<command> [on|off]
        aliases: [v,admin]
    fadmin:
        description: Tells admins to fuck off.
        usage: /<command> <admin>
        aliases: [doom]
    
    #Chats
    
    helperchat:
        description: Use the Helper chat.
        usage: /<command> [message]
        aliases: [hc, hchat]
    modchat:
        description: Use the Moderator chat.
        usage: /<command> [message]
        aliases: [mc, mchat]
    adminchat:
        description: Use the Admin chat.
        usage: /<command> [message]
        aliases: [ac, achat, o]
    devchat:
        description: Use the Developer chat.
        usage: /<command> [message]
        aliases: [dc, dchat]
    ownerchat:
        description: Use the Owner chat.
        usage: /<command> [message]
        aliases: [oc, ochat]
